# Generated by Django 2.0.1 on 2018-01-22 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storageadmin', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
