# Generated by Django 2.0.1 on 2018-01-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageadmin', '0008_auto_20180124_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_tb_per_day', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='storagevolume',
            name='storage_volume_path',
            field=models.CharField(default='Undefined', max_length=30),
            preserve_default=False,
        ),
    ]
