# Generated by Django 2.0.1 on 2018-03-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageadmin', '0009_auto_20180124_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageusage',
            name='storage_usage_quota',
            field=models.FloatField(default=1024),
        ),
    ]
