# Generated by Django 2.0.1 on 2018-03-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageadmin', '0010_storageusage_storage_usage_quota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storageusage',
            old_name='storage_usage_quota',
            new_name='storage_usage_quota_lustre',
        ),
        migrations.AddField(
            model_name='storageusage',
            name='storage_usage_quota_home',
            field=models.FloatField(default=512),
        ),
    ]
