# Generated by Django 2.0.1 on 2018-04-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageadmin', '0012_auto_20180330_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='groupleader',
        ),
        migrations.AddField(
            model_name='profile',
            name='quota_galaxy',
            field=models.FloatField(default=1024),
        ),
        migrations.AddField(
            model_name='profile',
            name='usage_galaxy',
            field=models.FloatField(default=1024),
        ),
        migrations.AddField(
            model_name='profile',
            name='usage_home',
            field=models.FloatField(default=1024),
        ),
        migrations.AddField(
            model_name='profile',
            name='usage_lustre',
            field=models.FloatField(default=1024),
        ),
        migrations.AlterField(
            model_name='profile',
            name='quota_home',
            field=models.FloatField(default=1024),
        ),
    ]
