# Generated by Django 2.0.1 on 2018-04-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageadmin', '0013_auto_20180417_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_group_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='quota_galaxy',
            field=models.FloatField(default=512),
        ),
        migrations.AlterField(
            model_name='profile',
            name='quota_home',
            field=models.FloatField(default=512),
        ),
        migrations.AlterField(
            model_name='profile',
            name='usage_galaxy',
            field=models.FloatField(default=512),
        ),
        migrations.AlterField(
            model_name='profile',
            name='usage_home',
            field=models.FloatField(default=512),
        ),
    ]
